{% set name = "winloop" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/winloop-{{ version }}.tar.gz
  sha256: 840c03b246a23d42c85de5c79c2df9f8e19e162c8caf80fdc2f3c1663e3f141b

build:
  skip: true  # [not win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=60
    - wheel
    - cython >=3.0,<4.dev0
    - pip
  run:
    - python

test:
  imports:
    - winloop
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Vizonex/Winloop
  summary: Windows version of uvloop
  license: Apache-2.0 AND MIT AND EPL-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - vendor/libuv/LICENSE
    - vendor/libuv/LICENSE-docs
    - vendor/libuv/LICENSE-extra

extra:
  recipe-maintainers:
    - owenlamont
